package vista;

import controlador.ControladorBotones;


public class FRM_Principal extends javax.swing.JFrame 
{
    private ControladorBotones controlador;
    
    public FRM_Principal() 
    {
        initComponents();
        
        controlador = new ControladorBotones(this);
        agregarEventos();
        setLocationRelativeTo(null);
        panel_EntregarFicha2.resetearPanelEntregar();
    }//Fin del constructor.

    public void mostrarAtendido(String cliente)
    {
        this.panel_LlamarCliente2.mostrarAtendido(cliente);
    }//Fin del metodo mostrarAtendido.
    
    public void mostrarInformacion(String arreglo[]){
    
        this.panel_EntregarFicha2.mostrarInformacion(arreglo);
    }
    
    public void mostrarLista(String lista)
    {
        this.panel_LlamarCliente2.mostrarLista(lista);
    }//Fin del metodo mostrarLista.
    
    public void resetearPanelEntregar()
    {
        this.panel_EntregarFicha2.resetearPanelEntregar();
    }//Fin del metodo resetearPanelEntregar.
    
    public String[] obtenerDatos()
    {
        return this.panel_EntregarFicha2.obtenerDatos();
    }//Fin del metodo obtenerDatos.
    
    public void agregarEventos()
    {
        this.panel_EntregarFicha2.agregarEventos(controlador);
        this.panel_LlamarCliente2.agregarEventos(controlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_EntregarFicha2 = new vista.Panel_EntregarCita();
        panel_LlamarCliente2 = new vista.Panel_LlamarCliente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_EntregarFicha2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(panel_LlamarCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_EntregarFicha2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(panel_LlamarCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.Panel_EntregarCita panel_EntregarFicha2;
    private vista.Panel_LlamarCliente panel_LlamarCliente2;
    // End of variables declaration//GEN-END:variables
}
