package vista;

import controlador.ControladorBotones;


public class Panel_LlamarCliente extends javax.swing.JPanel 
{
    public Panel_LlamarCliente() 
    {
        initComponents();
        txtArea_Lista.setEnabled(false);
    }//Fin del constructor.

    public void agregarEventos(ControladorBotones controlador)
    {
        this.btn_Llamar.addActionListener(controlador);
        this.btn_Menor.addActionListener(controlador);
        this.btn_Mayor.addActionListener(controlador);
    }
    
    public void mostrarAtendido(String cliente)
    {
        this.label_ClienteAtendido.setText("Cliente atendido: " + cliente);
    }//Fin del metodo mostrarAtendido.
    
    public void mostrarLista(String lista)
    {
        txtArea_Lista.setText("");
        txtArea_Lista.setText(lista);
    }//Fin del metodo mostrarLista.
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Llamar = new javax.swing.JButton();
        btn_Menor = new javax.swing.JButton();
        btn_Mayor = new javax.swing.JButton();
        scrollPane_txtArea_Lista = new javax.swing.JScrollPane();
        txtArea_Lista = new javax.swing.JTextArea();
        label_ClienteAtendido = new javax.swing.JLabel();

        btn_Llamar.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        btn_Llamar.setText("Atender a Siguiente");

        btn_Menor.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        btn_Menor.setText("Menor a Mayor");

        btn_Mayor.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        btn_Mayor.setText("Mayor a Menor");

        txtArea_Lista.setColumns(20);
        txtArea_Lista.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        txtArea_Lista.setRows(5);
        scrollPane_txtArea_Lista.setViewportView(txtArea_Lista);

        label_ClienteAtendido.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        label_ClienteAtendido.setText("Cliente atendido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollPane_txtArea_Lista)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Llamar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Menor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Mayor)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_ClienteAtendido)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Llamar)
                    .addComponent(btn_Menor)
                    .addComponent(btn_Mayor))
                .addGap(18, 18, 18)
                .addComponent(scrollPane_txtArea_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_ClienteAtendido)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Llamar;
    private javax.swing.JButton btn_Mayor;
    private javax.swing.JButton btn_Menor;
    private javax.swing.JLabel label_ClienteAtendido;
    private javax.swing.JScrollPane scrollPane_txtArea_Lista;
    private javax.swing.JTextArea txtArea_Lista;
    // End of variables declaration//GEN-END:variables
}
