package vista;

import controlador.ControladorBotones;

public class Panel_EntregarCita extends javax.swing.JPanel 
{
    private ControladorBotones controlador;
    
    public Panel_EntregarCita() 
    {
        initComponents();
    }//Fin del constructor.

    public void agregarEventos(ControladorBotones controlador)
    {
        this.controlador = controlador;
        this.btn_EntregarCita.addActionListener(controlador);
    }
    
    public void resetearPanelEntregar()
    {
        text_Cedula.setText("");
        txt_Nombre.setText("");
        txt_Edad.setText("");
        comboBox_Prioridad.setSelectedIndex(0);
    }//Fin del metodo resetearPanelEntregar.
    
    public String[] obtenerDatos()
    {
        String[] datosCliente = new String[4];
        
        datosCliente[0] = text_Cedula.getText();
        datosCliente[1] = txt_Nombre.getText();
        datosCliente[2] = txt_Edad.getText();
        datosCliente[3] = comboBox_Prioridad.getSelectedItem().toString();
        
        return datosCliente;
        
    }//Fin del metodo obtenerdatos.
    
    public void mostrarInformacion(String arreglo[]){
     
        
       text_Cedula.setText( arreglo[0]);
       txt_Nombre.setText( arreglo[1]);
       txt_Edad.setText( arreglo[2]);
    
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Nombre = new javax.swing.JLabel();
        label_Edad = new javax.swing.JLabel();
        label_Prioridad = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Edad = new javax.swing.JTextField();
        comboBox_Prioridad = new javax.swing.JComboBox<>();
        btn_EntregarCita = new javax.swing.JButton();
        label_Cedula = new javax.swing.JLabel();
        text_Cedula = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(504, 282));

        label_Nombre.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        label_Nombre.setText("Nombre");

        label_Edad.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        label_Edad.setText("Edad");

        label_Prioridad.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        label_Prioridad.setText("Prioridad");

        txt_Nombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N

        txt_Edad.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N

        comboBox_Prioridad.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        comboBox_Prioridad.setMaximumRowCount(3);
        comboBox_Prioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una prioridad", "7600", "Normal" }));

        btn_EntregarCita.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_EntregarCita.setText("Entregar Cita");

        label_Cedula.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        label_Cedula.setText("Cedula");

        btn_Buscar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_Buscar.setText("Buscar");

        btn_Cancelar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_Cancelar.setText("Cancelar");

        btn_Modificar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btn_Modificar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_Prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBox_Prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(text_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_EntregarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Modificar))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Cedula)
                    .addComponent(text_Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Nombre)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Edad)
                    .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Prioridad)
                    .addComponent(comboBox_Prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_EntregarCita)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Buscar)
                        .addComponent(btn_Cancelar)
                        .addComponent(btn_Modificar)))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_EntregarCita;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JComboBox<String> comboBox_Prioridad;
    private javax.swing.JLabel label_Cedula;
    private javax.swing.JLabel label_Edad;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_Prioridad;
    private javax.swing.JTextField text_Cedula;
    private javax.swing.JTextField txt_Edad;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}//Fin de la clase Panel_EntregarCita.
